### ISSUE TITLE
Incompatible shapes when using resnet as feature network

### ISSUE THREAD

**Issue by eleow** [eleow/tfKerasFRCNN#5]
![image](https://user-images.githubusercontent.com/4363234/68005852-a1794100-fcb1-11e9-8052-52e25a46f6ae.png)

**Comment by SergioPN** [comment]
Hello,
This still happens when using resnet50. Any solution?

**Comment by eleow** [comment]
> Hello,
> This still happens when using resnet50. Any solution?

What are your input parameters?

**Comment by SergioPN** [comment]
im_size=600
anchor_box_scales = [64,128,256] and [128,256,512]
class_mappings = {'bg': 1, 'base': 0}
anchor_box_ratios = default
num_anchors=9
num_rois = 256

no flips nor image augmentation of any kind
shuffle
base_net_type=resnet50


It is pretty much everything default except im_size.

Vgg works fine tho.

Thanks!
